version: '2'

services:
  web:
    image: registry.pmjlle.joinville.sc.gov.br:5000/ext/transnote:${CI_COMMIT_SHA}
    network_mode: bridge
    restart: "always"
    mem_limit: 1g
    ports:
      - "33000:8000"
    environment:
      - DB_NAME
      - USER_DB
      - PASSWORD_DB
      - HOST_DB
      - PORT_DB
      - VIRTUAL_HOST
    volumes:
      - /mnt/documents/${VIRTUAL_HOST}/media:/media
      - /mnt/documents/${VIRTUAL_HOST}/media/images:/media/images
      - /mnt/documents/${VIRTUAL_HOST}/media/infracao_images:/media/infracao_images
      - /mnt/documents/${VIRTUAL_HOST}/media/media:/media/media
